version: '3.7'

services: 
  currency-exchange:
    image: jovicicljubica/2023-currency-exchange:latest
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka     
      
  naming-server:
    image: jovicicljubica/2023-naming-server:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
      - user-network
      - crypto-network
      - trade-network
      - transfer-network
  
  users-service:
    image: jovicicljubica/2023-users-service:latest
    mem_limit: 700m
    ports:
      - "8770:8770"
    networks:
      - user-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  currency-conversion:
    image: jovicicljubica/2023-currency-conversion:latest
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - users-service
      - currency-exchange
      - bank-account
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  bank-account:
    image: jovicicljubica/2023-bank-account:latest
    mem_limit: 700m
    ports:
      - "8200:8200"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - users-service
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka  
      
  crypto-exchange:
    image: jovicicljubica/2023-crypto-exchange:latest
    mem_limit: 700m
    ports:
      - "8400:8400"
    networks:
      - crypto-network
    depends_on:
      - naming-server
      - users-service
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka

  crypto-conversion:
    image: jovicicljubica/2023-crypto-conversion:latest
    mem_limit: 700m
    ports:
      - "8500:8500"
    networks:
      - crypto-network
    depends_on:
      - naming-server
      - users-service
      - crypto-exchange
      - crypto-wallet
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
    
  crypto-wallet:
    image: jovicicljubica/2023-crypto-wallet:latest
    mem_limit: 700m
    ports:
      - "8300:8300"
    networks:
      - crypto-network
    depends_on:
      - naming-server
      - users-service
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      
  trade-service:
    image: jovicicljubica/2023-trade-service:latest
    mem_limit: 700m
    ports:
      - "8600:8600"
    networks:
      - trade-network
    depends_on:
      - naming-server
      - users-service
      - bank-account
      - crypto-wallet
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      
  transfer-service:
    image: jovicicljubica/2023-transfer-service:latest
    mem_limit: 700m
    ports:
      - "8700:8700"
    networks:
      - transfer-network
    depends_on:
      - naming-server
      - users-service
      - bank-account
      - crypto-wallet
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      
  api-gateway:
    image: jovicicljubica/2023-api-gateway:latest
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - user-network
    depends_on:
      - naming-server
      - users-service
      - currency-exchange
      - bank-account
      - currency-conversion
      - crypto-exchange
      - crypto-wallet
      - crypto-conversion
      - transfer-service
      - trade-service
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
          
 
networks:
  currency-network:
  user-network:
  crypto-network:
  trade-network:
  transfer-network: